controllers/album.py
from flask import *
import MySQLdb
import MySQLdb.cursors
from extensions import *
import hashlib
import os
from flask import Flask, request, redirect, url_for,session
from werkzeug.utils import secure_filename
from flask.ext.session import Session

def picidCreated(albumid, filename):
	m = hashlib.md5()
	m.update(str(albumid))
	m.update(filename)
	return m.hexdigest()

ALLOWED_EXTENSIONS = set(['png','jpg','bmp','gif'])

def allowed_file(filename):
   	return '.' in filename and \
   		filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS




album = Blueprint('album', __name__, template_folder='templates')

@album.route('/album/edit', methods=['GET', 'POST'])
def album_edit_route():
	options = {
		"edit": True
	}
	if 'username' in session: 
		
		username = session['username']
		
		if request.method != 'POST' and request.method !='GET':
			return abort(404)
		db = connect_to_database()
		cur = db.cursor()

	
		if request.method == 'GET':
			test_albumid = request.args.get('albumid', 'default_value')
			cur.execute("SELECT username FROM Album WHERE albumid='%s'" %test_albumid)
			results_username = cur.fetchall()
			if username != results_username[0]['username']:
				return abort(403)

			cur.execute("SELECT * FROM Album WHERE albumid='%s'" %test_albumid)
			results_search_album = cur.fetchall()

			
			flag = 0
			for item in results_search_album:
				if (item['albumid'] == int(test_albumid)) and (username == item['username']):
					flag = 1
			if flag == 0:
				return abort(404) 
		

		if request.method == 'POST':
			op = request.form.get('op', 'default_value')
			test_albumid = request.form.get('albumid', 'default_value')
			test_picid = request.form.get('picid', 'default_value')
			if op == 'add':
				if 'file' not in request.files:
					return redirect(request.url)
				file = request.files['file']

				if file.filename == '':
					return redirect(request.url)

				if file and allowed_file(file.filename):
				
					filename = secure_filename(file.filename)
					fileformat = os.path.splitext(filename)[1]	
					fileformat = fileformat[1:]
				

					picid = picidCreated(test_albumid, filename)

					cur.execute("SELECT MAX(sequencenum) FROM Contain")
					sequencenum = cur.fetchall()
					sequencenum = sequencenum[0]['MAX(sequencenum)']
					sequencenum = int(sequencenum) + 1

					cur.execute("INSERT INTO Photo (picid, format) VALUES ('%s', '%s')" %(picid, fileformat))
					cur.execute("INSERT INTO Contain (sequencenum, albumid, picid) VALUES ('%d','%s', '%s')" %(long(sequencenum), test_albumid, picid))

					filename = picid+'.'+fileformat

					file.save(os.path.join('./static/images/', filename))

			elif op == 'delete':
	
				cur.execute("SELECT format FROM Photo WHERE picid='"+test_picid+"'")
				formats = cur.fetchall()
				picformat = formats[0]['format']
			
				cur.execute("DELETE FROM Photo WHERE picid='%s'" %test_picid)
				fname = test_picid+'.'+picformat
				os.system("cd static/images && rm '%s'" %fname)
			elif op == 'access':
				access = request.form.get('access', 'default_value')
				cur.execute("UPDATE Album SET access = '"+access+"' WHERE albumid = '"+test_albumid+"' ")
				cur.execute("DELETE FROM AlbumAccess WHERE albumid = '"+test_albumid+"' ")

			elif op == 'revoke':
				username = request.form.get('username', 'default_value')
				cur.execute("DELETE FROM AlbumAccess WHERE albumid = '"+test_albumid+"' and username = '"+username+"'")

			elif op == 'grant':
				username = request.form.get('username', 'default_value')
				cur.execute("SELECT access FROM Album WHERE albumid='"+test_albumid+"'")
				access = cur.fetchall()[0]['access']
				if(access == 'private'):
					cur.execute("INSERT INTO AlbumAccess (albumid, username) VALUES ('%s', '%s')" %(test_albumid, username))


		cur.execute("SELECT * FROM Album WHERE albumid='%s'" %test_albumid)
		results_album = cur.fetchall()
		test_title = results_album[0]['title']

		cur.execute("SELECT * FROM Contain WHERE albumid='%s'" %test_albumid)
		results_contain = cur.fetchall()
	
		cur.execute("SELECT * FROM Photo WHERE picid IN (SELECT picid FROM Contain WHERE albumid = '"+test_albumid+"')")
		results_photo = cur.fetchall()

		cur.execute("SELECT username FROM AlbumAccess WHERE albumid='%s'" %test_albumid)
		results_search_access = cur.fetchall()

		cur.execute("SELECT * FROM User WHERE username='"+username+"'")
		results_user = cur.fetchall()
	
		return render_template('album.html',user = results_user, album_title = test_title, albumid = long(test_albumid), Photo = results_photo, access = results_search_access, username =username, **options)

	else:
		return render_template('login.html')

@album.route('/album', methods = ['GET', 'POST'])
def album_route():
	options = {
		"edit": False
	}
	if 'username' in session:
		username = session['username']
		test_albumid = request.args.get('albumid', 'default_value')

		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT * FROM Album WHERE albumid='%s'" %test_albumid)
		results_search_album = cur.fetchall()
		
		flag = 0
		for item in results_search_album:
			if (item['albumid'] == int(test_albumid)):
				flag = 1
		if flag == 0:
			return abort(404) 
		
		
		dbSearch = connect_to_database()
		curSearch = dbSearch.cursor()
		curSearch.execute("SELECT title FROM Album WHERE albumid='%s'" %test_albumid)
		results_title = curSearch.fetchall()
		curSearch.execute("SELECT username FROM Album WHERE albumid='%s'" %test_albumid)
		results_username = curSearch.fetchall()
		flag = False
		if username == results_username[0]['username']:
			flag = True
		curSearch.execute("SELECT access FROM Album WHERE albumid='%s'" %test_albumid)
		results_access = curSearch.fetchall()
		if(username!=results_username[0]['username'] and results_access[0]['access']== 'private'):
			db = connect_to_database()
			cur = db.cursor()
			cur.execute("SELECT username FROM AlbumAccess WHERE albumid='%s'" %test_albumid)
			results_search_username = cur.fetchall()
			flag_2 = 0
			for item in results_search_username:
				if (item['username'] == username):
					flag_2 = 1
			if flag_2 == 0:
				return abort(403) 



		db = connect_to_database()
		cur = db.cursor()
		
		cur.execute("SELECT * FROM Contain WHERE albumid = '%s'" %test_albumid)
		results_contain = cur.fetchall()
		
		cur.execute("SELECT * FROM Photo WHERE picid IN (SELECT picid FROM Contain WHERE albumid = '"+test_albumid+"')")
		results_photo = cur.fetchall()

		cur.execute("SELECT * From User WHERE username='"+username+"'")
		results_user = cur.fetchall()

		return render_template('album.html',user = results_user, album_title = results_title[0]['title'],albumid = test_albumid, Photo = results_photo, username = username, other_username = results_username[0]['username'],flag = flag,**options)
		



	else:
		'''
		if request.method != 'POST' and request.method !='GET':
			return abort(404)
		'''
		test_albumid = request.args.get('albumid', 'default_value')
		
		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT username FROM Album WHERE albumid='%s'" %test_albumid)
		username = cur.fetchall()
		cur.execute("SELECT * FROM Album WHERE albumid='%s'" %test_albumid)
		results_search_album = cur.fetchall()
		flag = 0
		for item in results_search_album:
			if (item['albumid'] == int(test_albumid)):
				flag = 1
		if flag == 0:
			return abort(404) 


		dbSearch = connect_to_database()
		curSearch = dbSearch.cursor()
		curSearch.execute("SELECT title FROM Album WHERE albumid='%s'" %test_albumid)
		results_title = curSearch.fetchall()
		curSearch.execute("SELECT access FROM Album WHERE albumid='%s'" %test_albumid)
		results_access = curSearch.fetchall()
		
		if(results_access[0]['access']=='public'):
			db = connect_to_database()
			cur = db.cursor()
			cur.execute("SELECT * FROM Contain WHERE albumid = '%s'" %test_albumid)
			results_contain = cur.fetchall()

			cur.execute("SELECT * FROM Photo WHERE picid IN (SELECT picid FROM Contain WHERE albumid = '"+test_albumid+"')")
			results_photo = cur.fetchall()

			return render_template('album_public.html', album_title = results_title[0]['title'],albumid = test_albumid, Photo = results_photo, username = username[0]['username'],**options)
		else:
			return render_template('login.html')

controllers/albums.py
from flask import *
import MySQLdb
import MySQLdb.cursors
from extensions import *
import os
from flask import Flask, session
from flask.ext.session import Session

albums = Blueprint('albums', __name__, template_folder='templates')

@albums.route('/albums/edit', methods=['GET', 'POST'])
def albums_edit_route():
	options = {
		"edit": True
	}
	if 'username' in session:
		
		username = session['username']
		
		if request.method != 'POST' and request.method !='GET':
			return abort(404)
		
		'''
		url_username = request.args.get('username', 'default_value')
		if(url_username != username):
			return abort(404)
		'''
		db = connect_to_database()
		cur = db.cursor()
			
		
		#username = session['username']

		if request.method == 'POST':
			op = request.form['op']
			if op == 'add':
				title = request.form['title']
				username = request.form['username']
				#createalbum = request.form['createalbum']
				cur.execute("INSERT INTO Album (title, username) Values ('%s', '%s')" %(title, username))
			elif op == 'delete':
				albumid = request.form['albumid']
				cur.execute("SELECT picid FROM Contain WHERE albumid = '%s'" %albumid)
				results_search = cur.fetchall()
				for item in results_search:
					cur.execute("DELETE FROM Photo WHERE picid = '%s'" %item['picid'])
					filename = item['picid']
					filename = filename + '.jpg'
					targetFile = os.path.join('./static/images/', filename)
					os.remove(targetFile)

				cur.execute("DELETE FROM Album WHERE albumid = '%s'" %albumid)
		
		cur.execute("SELECT * FROM Album WHERE username = '%s'" %username)

		results_albums = cur.fetchall()
		cur.execute("SELECT * FROM User WHERE username='"+username+"'")
		results_user = cur.fetchall()
		
		return render_template("albums.html",user = results_user, Albums = results_albums, username = username, **options)
	else:
		return render_template('login.html')


@albums.route('/albums', methods=['GET', 'POST'])
def albums_route():
	options = {
		"edit": False
	}

	if 'username' in session:

		username = session['username']
		
				
		db = connect_to_database()
		cur = db.cursor()
			
		cur.execute("SELECT * FROM Album WHERE username = '"+username+"'")
		results_albums = cur.fetchall()
		cur.execute("SELECT * FROM Album WHERE albumid in (SELECT albumid FROM AlbumAccess WHERE username = '"+username+"')")
		other_albums = cur.fetchall()
		cur.execute("SELECT * FROM User WHERE username = '"+username+"'")
		results_user = cur.fetchall()

		return render_template('albums.html',user = results_user, username = username, Albums = results_albums, other_albums = other_albums, **options)

	else:
		if request.method != 'POST' and request.method !='GET':
			return abort(404)
		username = request.args.get('username', 'default_value')

		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT * FROM User WHERE username='%s'" %username)
		results_search_user = cur.fetchall()
		flag = 0
		for item in results_search_user:
			if item['username'] == username:
				flag = 1
		if flag == 0:
			return abort(404)


		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT * FROM Album WHERE access = 'public' AND username = '"+username+"'")
		results_albums = cur.fetchall()
		return render_template('albums_public.html', Albums = results_albums, username = username, **options)

controllers/login.py
from flask import *
import MySQLdb
import MySQLdb.cursors
from extensions import *
import hashlib
import uuid
from flask import Flask, session
from flask.ext.session import Session

def passwordCreated(password):
	algorithm = 'sha512'
	salt = uuid.uuid4().hex
	print salt

	m = hashlib.new(algorithm)
	m.update(salt + password)
	password_hash = m.hexdigest()

	return "$".join([algorithm, salt, password_hash])

login = Blueprint('login', __name__, template_folder='templates')

def passwordCheck(salt, password):
	algorithm = 'sha512'
	m = hashlib.new(algorithm)
	m.update(salt + password)
	password_hash = m.hexdigest()

	return "$".join([algorithm, salt, password_hash])

login = Blueprint('login', __name__, template_folder='templates')

@login.route('/login', methods = ['GET', 'POST'])
def login_route():
	if (request.method == 'GET'):
		return render_template("login.html")   
	elif (request.method == 'POST'):
		username = request.form.get('username', 'default_value')
		password = request.form.get('password', 'default_value')

		errors = {
			"error" : False,
			"usernameBlank" : False,
			"passwordBlank" : False,
			"usernameDoesNotExist" : False,
			"passwordIncorrect" : False
		}

		if username == "":
			errors['error'] = True
			errors['usernameBlank'] = True
		if password == "":
			errors['error'] = True
			errors['passwordBlank'] = True

		if username != "":
			db = connect_to_database()
			cur = db.cursor()
			cur.execute("SELECT password FROM User WHERE username='"+username+"'")
			results_password = cur.fetchall()
			if results_password == ():
				errors['error'] = True
				errors['usernameDoesNotExist'] = True
			else:
				salt = results_password[0]['password'].rsplit('$', 2)[1]
				password = passwordCheck(salt, password)

				if password != results_password[0]['password']:
					errors['error'] = True
					errors['passwordIncorrect'] = True
				else:
					session['username'] = username
		if errors['error']:
			return render_template('login.html', **errors)
		else:			
			return redirect(url_for('main.main_route', username = username))

controllers/logout.py
from flask import *
import MySQLdb
import MySQLdb.cursors
from extensions import *
import os
from flask import Flask, session
from flask.ext.session import Session


logout = Blueprint('logout', __name__, template_folder='templates')

@logout.route('/logout', methods = ['GET', 'POST'])
def logout_route():
	session.pop('username', None)
	return redirect(url_for('main.main_route'))

controllers/pic.py
from flask import *
import MySQLdb
import MySQLdb.cursors
from extensions import *
from flask import Flask, session
from flask.ext.session import Session

pic = Blueprint('pic', __name__, template_folder='templates')

@pic.route('/pic', methods = ['GET', 'POST'])
def pic_route():
	
	if request.method != 'POST' and request.method !='GET':
		return abort(404)
	if request.method == 'GET':
		picid = request.args.get('picid', 'default_value')
		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT * FROM Photo WHERE picid='%s'" %picid)
		results_search_photo = cur.fetchall()
		flag = 0
		for item in results_search_photo:
			if item['picid'] == picid:
				flag = 1
		if flag == 0:
			return abort(404)

		test_picid = request.args.get('picid', 'default_value')

		db = connect_to_database()
		cur = db.cursor()
		cur.execute("SELECT * FROM Contain WHERE picid='%s'" %test_picid)
		results_search = cur.fetchall()
		caption = results_search[0]['caption']
		cur.execute("SELECT * FROM Photo WHERE picid='%s'" %test_picid)
		results_photo = cur.fetchall()
		format = results_photo[0]['format'] 

		test_albumid = results_search[0]['albumid']

		cur.execute("SELECT * FROM Album WHERE albumid IN (SELECT albumid FROM Contain WHERE picid = '"+test_picid+"')")
		test_album = cur.fetchall()

		flag_1=False
		if 'username' in session:
			username = session['username']
			if(username!=test_album[0]['username'] and test_album[0]['access']== 'private'):
				db = connect_to_database()
				cur = db.cursor()
				cur.execute("SELECT username FROM AlbumAccess WHERE albumid='%s'" %test_albumid)
				results_search_username = cur.fetchall()
				flag_2 = 0
				for item in results_search_username:
					if (item['username'] == username):
						flag_2 = 1
				if flag_2 == 0:
					return abort(403)

			elif(username == test_album[0]['username']):
				flag_1= True

			cur.execute("SELECT * FROM User WHERE username='"+username+"'")
			results_user = cur.fetchall()

		else:
			results_user = None
			if(test_album[0]['access']== 'private'):
				return render_template('login.html')

		cur.execute("SELECT * FROM Contain WHERE albumid='%s'" %test_albumid)
		test_contain_selected = cur.fetchall()

		

		return render_template('pic.html',user = results_user, albumid = test_albumid, picid =test_picid, format = format, Contain = test_contain_selected,caption = caption,flag_1 = flag_1)

	elif request.method == 'POST':
		flag_1=True
		if 'username' in session:
			op = request.form.get('op', 'default_value')
			caption = request.form.get('caption', 'default_value')
			picid = request.form.get('picid', 'default_value')
			if op == 'caption':
				db = connect_to_database()
				cur = db.cursor()
				cur.execute("UPDATE Contain SET caption = '"+caption+"' WHERE picid = '"+picid+"'")
				cur.execute("SELECT * FROM Contain WHERE picid='%s'" %picid)
				results_search = cur.fetchall()
				caption = results_search[0]['caption']
				cur.execute("SELECT * FROM Photo WHERE picid='%s'" %picid)
				results_photo = cur.fetchall()
				format = results_photo[0]['format'] 
				test_albumid = results_search[0]['albumid']
				cur.execute("SELECT * FROM Contain WHERE albumid='%s'" %test_albumid)
				test_contain_selected = cur.fetchall()
			return render_template('pic.html', albumid = test_albumid, picid =picid, format = format, Contain = test_contain_selected,caption = caption,flag_1 = flag_1)

templates/album.html
{% extends "base.html" %}
{% block content %}

	<a href="{{url_for('main.main_route', username = username)}}"
				id="nav_home">
	<botton>Back to Home</botton></a><br><br>

	<a href="{{url_for('user.user_edit_route',username = username)}}" id="nav_edit">
		Edit Account
	</a><br><br>
		
	<a href="{{url_for('albums.albums_route')}}" id = "nav_albums">
		My Albums
	</a><br><br>

	<a href="{{url_for('logout.logout_route')}}" id = "nav_logout">
		Log Out
	</a><br><br><br><br>


	{% if flag %}
	<h1>{{album_title}}, {{username}}</h1>
		<div>
			<a href="{{url_for('album.album_edit_route', albumid = albumid)}}" id="user_album_edit_{{albumid}}">
				<button>EDIT ALBUM</button>
			</a>
		</div><br>
	{% else %}
	<h1>{{album_title}}, {{_username}}</h1>
	{% endif %}

	{% if edit %}

	    <form action="" method="POST">
			<input type="radio" name="access" value="public" id="album_edit_public_radio">Public<br />
			<input type="radio" name="access" value="private" id="album_edit_private_radio">Private<br />
			<input type="hidden" name="albumid" value="{{albumid}}">
			<input type="submit" name="op" value="access" id="album_edit_access_submit">
		</form>

		<div><table>
		     <tr><th>Username</th><th>Update Access</th></tr>
	         {% for item in access %}
	         <form action="" method="POST">
	         <tr><td>{{item.username}}</td>
	             <td><input type="submit" name="op" value="revoke" id="album_edit_revoke_{{item.username}}">
	                 <input type = "hidden" name="albumid" value="{{albumid}}">
	                 <input type="hidden" name="username" value="{{item.username}}">
	                 </td>
	                 </tr>
	         </form>
	        {% endfor %}

	         <form action="" method="POST">
	         <tr><td>New:
	             <input type="text" name="username" id="album_edit_grant_input">
	             <input type = "hidden" name="albumid" value="{{albumid}}">
	             <input type="submit" name="op" value="grant" id="album_edit_grant_submit"></td></tr></form>
	         </table>
	    </div>
	         

	{% endif %}

	{% for item in Photo %}
		<div>{{item.picid}}
			<a href="{{url_for('pic.pic_route', picid = item.picid)}}" id="pic_{{item.picid}}_link">
			{% set filename = "images/" ~ item.picid ~  "." ~ item.format %}	
			<img src = "{{url_for('static',filename = filename)}}">

			</a>

			{% if edit %}
				<form action="" method="POST">
					<input type="hidden" name="albumid" value="{{albumid}}">
					<input type="hidden" name="picid" value="{{item.picid}}">
					<input type="submit" name="op" value="delete" id="delete_pic_{{item.picid}}">
				</form>
			{% endif %}

		</div><br>
	{% endfor %}

	{% if edit %}
		<form action="" method="POST" enctype="multipart/form-data">
			NEW PIC:
			<input type="hidden" name="albumid" value="{{albumid}}">
			<input type="file" name="file" id="file_input">
			<input type="submit" name="op" value="add" id="file_submit">
			
		</form>>
	{% endif %}
{% endblock %}

templates/album_public.html
{% extends "base.html" %}
{% block content %}
<h1>{{album_title}}, {{username}}</h1>

	{% for item in Photo %}
		 <strong>{{item.picid}}</strong>
		 <a href="{{url_for('pic.pic_route', picid = item.picid)}}" id="pic_{{item.picid}}_link">
			{% set filename = "images/" ~ item.picid ~  "." ~ item.format %}	
			<img src = "{{url_for('static',filename = filename)}}">
		 </a>
	{% endfor %}

{% endblock %}

templates/albums.html
{% extends "base.html" %}
{% block content %}
	
	<a href="{{url_for('main.main_route', username = username)}}"
				id="nav_home">
	<botton>Back to Home</botton></a><br><br>

	<a href="{{url_for('user.user_edit_route',username = username)}}" id="nav_edit">
		Edit Account
	</a><br><br>
		
	<a href="{{url_for('albums.albums_route')}}" id = "nav_albums">
		My Albums
	</a><br><br>

	<a href="{{url_for('logout.logout_route')}}" id = "nav_logout">
		Log Out
	</a><br><br><br><br>

	<strong>
		{{username}}
	</strong>
	<div>
		<a href="{{url_for('albums.albums_edit_route')}}"
		id="user_albums_edit_{{username}}">
		<button>EDIT ALBUMS</button></a>
	</div><br>

	{% for item in Albums%}
		<div>{{item.title}}
			<a href="{{url_for('album.album_route', albumid = item.albumid)}}"  id="album_{{item.albumid}}_link">
			<button>{{item.title}}</button>
			</a>
			<a href="{{url_for('album.album_edit_route', albumid = item.albumid)}}" id="album_edit_{{item.albumid}}_link">
			<button>EDIT</button>
			</a>

			{% if edit %}
				<form action="" method="POST">
					<input type="hidden" name="albumid" value="{{item.albumid}}">
					<input type="submit" name="op" value="delete" id="delete_album_{{item.albumid}}">

				</form>
			{% endif %}

		</div><br>
	{% endfor %}

	{% for item in other_albums%}
		<div>{{item.title}}
			<a href="{{url_for('album.album_route', albumid = item.albumid)}}"  id="album_{{item.albumid}}_link">
			<button>{{item.title}}</button>
			</a>

		</div><br>
	{% endfor %}


	{% if edit %}
		<form action="" method="POST">
			NEW ALBUM:
			<input type="text" name="title" id="album_add_title">
			<input type="hidden" name="username" value="{{username}}" id="album_add_username">
			<input type="submit" name="op" value="add" id="album_add_submit">
			
		</form>	
	{% endif %}
{% endblock %}

templates/albums_public.html
{% extends "base.html" %}
{% block content %}

	<h1>All Public Albums Of {{username}}</h1>
	    {% for item in Albums%}
		<div>{{item.title}}
			<a href="{{url_for('album.album_route', albumid = item.albumid,username = username)}}" id="album_{{item.albumid}}_link">
			<button>{{item.title}}</button>
			</a>
		</div>
		{% endfor %}
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block content %}
	<h1>Hello, Jennifer</h1>

		<a href="{{url_for('login.login_route')}}" id="home_login">
			Log In
		</a><br>
		<a href="{{url_for('user.user_route')}}" id="home_user_create">
			Create New Account
		</a><br><br><br>
		

		<strong>
			Click On The Following Links To View All Public Albums
		</strong><br>

		{% for items in album%}
		<br>
		<a href="{{url_for('album.album_route', albumid=items['albumid'])}}" id="album_{{items.albumid}}_link">
			<strong>
				{{items['title']}}
			</strong>		
		</a>
		{% endfor %}
		<br><br><br>

	

		<strong>
			Click On The Following Links To View Public/Shared Albums of Each User
		</strong><br>
		{% for items in user%}
		<br>
		<a href="{{url_for('albums.albums_route', username=items['username'])}}" id="user_albums_{{items['username']}}">		
			<strong>
				{{items['username']}}
			</strong>		
		</a>
		{% endfor %}
		<br><br><br>

	<footer>EECS 485 PROJECT 1 CREATED BY GROUP 19</footer>
{% endblock %}

templates/logedin_home.html
{% extends "base.html" %}
{% block content %}
	<h1>Logged in as {{user[0]['firstname']}} {{user[0]['lastname']}}</h1>

	<a href="{{url_for('main.main_route', username = user[0]['username'])}}"
				id="nav_home">
	<botton>Back to Home</botton></a><br><br>
    
    <a href="{{url_for('user.user_edit_route',username = user[0]['username'])}}" id="nav_edit">
		Edit Account
	</a><br>
	<br>
	<a href="{{url_for('albums.albums_route')}}" id = "nav_albums">
		My Albums
	</a><br>
	<br>
	<a href="{{url_for('logout.logout_route')}}" id = "nav_logout">
		Log Out
	</a><br>
	<br><br><br>

	<strong>
		This is your own albums
	</strong><br><br>
	{% for item in Albums %}
		<div>
			<a href="{{url_for('album.album_route', albumid = item.albumid)}}"  id="album_{{item.albumid}}_link">
			{{item.title}}
			</a>
		</div><br>
	{% endfor %}
	<br><br><br>




	<strong>
		This is the albums which you have been granted access to by the owner
	</strong><br><br>
	{% for item in other_albums %}
		<div>
			<a href="{{url_for('album.album_route', albumid = item.albumid)}}"  id="album_{{item.albumid}}_link">
			{{item.title}}
			</a>

		</div><br>
	{% endfor %}
	<br>




	<strong>
		This is the public albums
	</strong><br>
	{% for items in AlbumPublic %}
		<br>
		<a href="{{url_for('album.album_route', albumid=items['albumid'])}}" id="album_{{items.albumid}}_link">
				{{items['title']}}
		</a><br>
	{% endfor %}
	<br><br><br>



	
{% endblock %}

templates/pic.html
{% extends "base.html" %}
{% block content %}
	{% if flag_1 %}
	{% endif %}
	<h1>{{picid}}</h1>
	<p id="pic_{{picid}}_caption">Caption: {{caption}}</p><br>

	{% if flag_1 %}
	<form action="" method="POST">
	  <input type="text" name="caption" id="pic_caption_input">
	  <input type="hidden" name="picid" value="{{picid}}">
      <input type="submit" name="op" value="caption" id="pic_caption_submit">
    </form>
    {% endif %}

	{% set filename = "images/" ~ picid ~ "." ~ format %}
	
	<img src = "{{url_for('static',filename = filename)}}"><br>

	{% for items in Contain %}
		{% if items['picid'] == picid %}
			{% set count = loop.index0 %}

			{% if not loop.first %}
				<a href="{{url_for('pic.pic_route', picid = Contain[count-1]['picid'])}}" id="prev_pic">
					<button>Previous PIC</button>
				</a>
			{% endif %}

			{% if not loop.last %}
				<a href="{{url_for('pic.pic_route', picid = Contain[count+1]['picid'])}}" id="next_pic">
					<button>Next PIC</button>
				</a>
			{% endif %}
			<a href="{{url_for('album.album_route', albumid= Contain[0]['albumid'])}}" id="parent_album">
				<button>BACK</button>
			</a>

		{% endif %}
	{% endfor %}
{% endblock %}